[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=root

[program:mysql]
command=/usr/sbin/mysqld --datadir=/muemu-data/mysql --user=mysql
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:connectserver]
command=dotnet /opt/muemu/connectserver/CSEmu.dll
directory=/opt/muemu/connectserver
autostart=true
autorestart=true
priority=20
startsecs=10
startretries=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:gameserver]
command=dotnet /opt/muemu/gameserver/MuEmu.dll
directory=/opt/muemu/gameserver
autostart=true
autorestart=true
priority=30
startsecs=15
startretries=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
