// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetGames():Promise<Array<main.GameCard>>;

export function InstallGame(arg1:main.GameCard):Promise<void>;

export function IsInstalled(arg1:string,arg2:string):Promise<boolean>;

export function LaunchGame(arg1:main.GameCard):Promise<void>;

export function OpenInstallFolder(arg1:string):Promise<void>;
