// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function InstallGame(arg1) {
  return window['go']['main']['App']['InstallGame'](arg1);
}

export function IsInstalled(arg1, arg2) {
  return window['go']['main']['App']['IsInstalled'](arg1, arg2);
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function OpenInstallFolder(arg1) {
  return window['go']['main']['App']['OpenInstallFolder'](arg1);
}
