// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdate(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CommunityHere():Promise<void>;

export function CommunitySend(arg1:string):Promise<main.CommunityMessage>;

export function CommunitySnapshot():Promise<main.CommunitySnapshot>;

export function GetGames():Promise<Array<main.GameCard>>;

export function GetMetin2Settings(arg1:main.GameCard):Promise<main.Metin2Settings>;

export function GetMuServers(arg1:main.GameCard):Promise<Array<main.MuServerInfo>>;

export function GetSettings(arg1:main.GameCard):Promise<main.GameSettings>;

export function InstallGame(arg1:main.GameCard):Promise<void>;

export function IsGameRunning(arg1:string):Promise<boolean>;

export function IsInstalled(arg1:string,arg2:string):Promise<boolean>;

export function Login(arg1:main.GameCard,arg2:string,arg3:string):Promise<string>;

export function OpenInstallFolder(arg1:string):Promise<void>;

export function Play(arg1:main.GameCard,arg2:string,arg3:string):Promise<void>;

export function PlayMu(arg1:main.GameCard,arg2:number):Promise<void>;

export function PlayerLink(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PlayerLogin(arg1:string,arg2:string):Promise<main.PlayerSession>;

export function PlayerLogout():Promise<void>;

export function PlayerMe():Promise<main.PlayerSession>;

export function PlayerRegister(arg1:string,arg2:string):Promise<main.PlayerSession>;

export function Register(arg1:main.GameCard,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveMetin2Settings(arg1:main.GameCard,arg2:main.Metin2Settings):Promise<void>;

export function SaveSettings(arg1:main.GameCard,arg2:main.GameSettings):Promise<void>;

export function ShopBuy(arg1:string,arg2:string):Promise<main.ShopBuyResult>;

export function ShopCatalog(arg1:string):Promise<Array<main.ShopItem>>;

export function Version():Promise<string>;
