// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CommunityHere() {
  return window['go']['main']['App']['CommunityHere']();
}

export function CommunitySend(arg1) {
  return window['go']['main']['App']['CommunitySend'](arg1);
}

export function CommunitySnapshot() {
  return window['go']['main']['App']['CommunitySnapshot']();
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetMetin2Settings(arg1) {
  return window['go']['main']['App']['GetMetin2Settings'](arg1);
}

export function GetSettings(arg1) {
  return window['go']['main']['App']['GetSettings'](arg1);
}

export function InstallGame(arg1) {
  return window['go']['main']['App']['InstallGame'](arg1);
}

export function IsGameRunning(arg1) {
  return window['go']['main']['App']['IsGameRunning'](arg1);
}

export function IsInstalled(arg1, arg2) {
  return window['go']['main']['App']['IsInstalled'](arg1, arg2);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function OpenInstallFolder(arg1) {
  return window['go']['main']['App']['OpenInstallFolder'](arg1);
}

export function Play(arg1, arg2, arg3) {
  return window['go']['main']['App']['Play'](arg1, arg2, arg3);
}

export function PlayerLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlayerLink'](arg1, arg2, arg3);
}

export function PlayerLogin(arg1, arg2) {
  return window['go']['main']['App']['PlayerLogin'](arg1, arg2);
}

export function PlayerLogout() {
  return window['go']['main']['App']['PlayerLogout']();
}

export function PlayerMe() {
  return window['go']['main']['App']['PlayerMe']();
}

export function PlayerRegister(arg1, arg2) {
  return window['go']['main']['App']['PlayerRegister'](arg1, arg2);
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4);
}

export function SaveMetin2Settings(arg1, arg2) {
  return window['go']['main']['App']['SaveMetin2Settings'](arg1, arg2);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function ShopBuy(arg1, arg2) {
  return window['go']['main']['App']['ShopBuy'](arg1, arg2);
}

export function ShopCatalog(arg1) {
  return window['go']['main']['App']['ShopCatalog'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
