// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdate(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function GetGames():Promise<Array<main.GameCard>>;

export function GetSettings(arg1:main.GameCard):Promise<main.GameSettings>;

export function InstallGame(arg1:main.GameCard):Promise<void>;

export function IsGameRunning(arg1:string):Promise<boolean>;

export function IsInstalled(arg1:string,arg2:string):Promise<boolean>;

export function Login(arg1:main.GameCard,arg2:string,arg3:string):Promise<string>;

export function OpenInstallFolder(arg1:string):Promise<void>;

export function Play(arg1:main.GameCard,arg2:string,arg3:string):Promise<void>;

export function Register(arg1:main.GameCard,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveSettings(arg1:main.GameCard,arg2:main.GameSettings):Promise<void>;

export function Version():Promise<string>;
